# http://wiki.ros.org/diff_drive_controller
my_robo:
  diff_drive_controller:
    type        : "diff_drive_controller/DiffDriveController"
    left_wheel  : 'left_wheel_joint'
    right_wheel : 'right_wheel_joint'
    publish_rate: 50.0               # default: 50
    wheel_separation : 0.285
    wheel_radius : 0.075
    num_pulse_per_meter : 10864.977448                      # 5120 / (M_PI * 2 * wheel_radius)
    pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

    # Wheel separation and diameter. These are both optional.
    # diff_drive_controller will attempt to read either one or both from the
    # URDF if not specified as a parameter

    # Wheel separation and radius multipliers
    # wheel_separation_multiplier: 1.0 # default: 1.0
    # wheel_radius_multiplier    : 1.0 # default: 1.0

    # Velocity commands timeout [s], default 0.5
    cmd_vel_timeout: 10.0

    # Base frame_id
    base_frame_id: base_footprint
    # default: base_link
    odom_frame_id: odom

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear:
      x:
        has_velocity_limits    : true
        max_velocity           : 0.5  # m/s
        min_velocity           : -0.5 # m/s
        has_acceleration_limits: true
        max_acceleration       : 20.0  # m/s^2
        min_acceleration       : -20.0 # m/s^2
    angular:
      z:
        has_velocity_limits    : true
        max_velocity           : 2.0  # rad/s
        min_velocity           : -2.0
        has_acceleration_limits: true
        max_acceleration       : 70.2  # rad/s^2
        min_acceleration       : -70.2
